[package]
name = "backend"
version = "0.1.0"
authors = ["Justas Dabrila <justasdabrila@gmail.com>"]

[lib]
name = "backend"
crate-type = ["dylib"]

[dependencies]
rusqlite = "0.13.0"
walkdir = "2.1.4"
notify = "4.0.0"
