[package]
name = "backend"
version = "0.1.0"
authors = ["Justas Dabrila <justasdabrila@gmail.com>"]

[dependencies]
models = { path = "../models", version = "*" }

serde = "1"
serde_derive = "1"
notify = "4.0.0"
chrono = "0.4.2"

[dependencies.rusqlite]
rusqlite = "0.13.0"
features = ["bundled"]
