[package]
name = "backend-api"
version = "0.1.0"
authors = ["Justas Dabrila <justasdabrila@gmail.com>"]

[dependencies]
backend = { path = "../backend", version = "*" }
hyper = "0.11.27"
futures = "0.1.21"
serde_json = "1"
serde_derive = "1"
serde = "1"
