[package]
name = "prod"
version = "0.1.0"
authors = ["Justas Dabrila <justasdabrila@gmail.com>"]

[dependencies]
backend-api = { path = "../backend-api", version = "*" }
open="1.2.1"
ctrlc = { version = "3.0", features = ["termination"] }
